---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
    exclude_fingerprints:
      - 0ef8b864f12a4be5203241ebd995122a
      - c5fcb6214e4424634eb97620e464e95c
      - 1fe3617134d14e530a225511897d7b3a
      - dae3a7ae438bdb514796e4a58ddb670b
      - dae3a7ae438bdb514796e4a58ddb670b
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      wrap-iife:
        enabled: false
    exclude_fingerprints:
      - f9d76cf12e1bd7a700a2f82299e6004e
  fixme:
    enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - build/**/*
  - design/**/*
  - wire/**/*
  - app/js/vendor/**/*
  - "app/js/components/ajaxRequest.js"
  - hologram-UI/**/*
- "client-server-communication%2Fremote.js"